#!/usr/bin/env bash

PKG_NAME=${PKG_NAME:-gardenlinux-selinux-module}
PKG_VERSION=${PKG_VERSION:-1.0.0}

mkdir _output
cp -r ${PKG_NAME} _output/.
cd _output

tar czf ${PKG_NAME}_${PKG_VERSION}.orig.tar.gz -C ${PKG_NAME} gardenlinux-selinux-module.te Makefile

cd ${PKG_NAME}

dpkg-buildpackage -us -uc -S -nc -d